### ISSUE TITLE
[BUG] - Couldn't get it to work  

### ISSUE THREAD

**Issue by sanfx** [calvinbui/homer-service-discovery#9]
**Describe the bug**
New service is not getting added even after adding label to docker container running on the same network

**To Reproduce**
Steps to reproduce the behaviour:
1. i created base.yml and config.yml for homer
2. Started homer  container loadsup fine with config.yml 
3. started homer-sd container on same network as homer  '....'
4. See log

```
# docker service logs  dashboards_homer-sd
dashboards_homer-sd.1.6zdppva9ud9m@swarm-master    | 11:59AM DBG Loading internal config
dashboards_homer-sd.1.6zdppva9ud9m@swarm-master    | 11:59AM INF Building Homer config from base config
dashboards_homer-sd.1.6zdppva9ud9m@swarm-master    | 11:59AM INF Homer config was successfully generated and updated
dashboards_homer-sd.1.6zdppva9ud9m@swarm-master    | 11:59AM INF Start watching for container creations and deletions
dashboards_homer-sd.1.6zdppva9ud9m@swarm-master    | 11:59AM INF Event 'start' received from dashboards_homer.1.lks2ch79joktgvs3cfd9nvq2a. Generating Homer config...
dashboards_homer-sd.1.6zdppva9ud9m@swarm-master    | 11:59AM INF Homer config was successfully generated and updated
dashboards_homer-sd.1.6zdppva9ud9m@swarm-master    | 11:59AM INF Event 'health_status: healthy' received from dashboards_homer.1.lks2ch79joktgvs3cfd9nvq2a. Generating Homer config...
dashboards_homer-sd.1.6zdppva9ud9m@swarm-master    | 11:59AM INF Homer config was successfully generated and updated
dashboards_homer-sd.1.6zdppva9ud9m@swarm-master    | 12:00PM INF Event 'die' received from traefik_reverse-proxy.3rqeb31c9upeocahsfbbcob5x.n5hs805nmgvi2jhr9ni7xn48l. Generating Homer config...
dashboards_homer-sd.1.6zdppva9ud9m@swarm-master    | 12:00PM INF Homer config was successfully generated and updated
dashboards_homer-sd.1.6zdppva9ud9m@swarm-master    | 12:00PM INF Event 'start' received from traefik_reverse-proxy.3rqeb31c9upeocahsfbbcob5x.zd4gg2jrl7xey1qhml0hc3a7p. Generating Homer config...
dashboards_homer-sd.1.6zdppva9ud9m@swarm-master    | 12:00PM INF Homer config was successfully generated and updated
dashboards_homer-sd.1.6zdppva9ud9m@swarm-master    | 12:12PM INF Event 'health_status: unhealthy' received from frontends_dashy.1.a72bzyx54bq7trtz6wabdkdno. Generating Homer config...
dashboards_homer-sd.1.6zdppva9ud9m@swarm-master    | 12:12PM INF Homer config was successfully generated and updated
dashboards_homer-sd.1.6zdppva9ud9m@swarm-master    | 12:12PM INF Event 'die' received from frontends_dashy.1.a72bzyx54bq7trtz6wabdkdno. Generating Homer config...
dashboards_homer-sd.1.6zdppva9ud9m@swarm-master    | 12:12PM INF Homer config was successfully generated and updated
dashboards_homer-sd.1.6zdppva9ud9m@swarm-master    | 12:12PM INF Event 'start' received from frontends_dashy.1.rxvia8fimadhrd6fdu07dqiz0. Generating Homer config...
dashboards_homer-sd.1.6zdppva9ud9m@swarm-master    | 12:12PM INF Homer config was successfully generated and updated
dashboards_homer-sd.1.6zdppva9ud9m@swarm-master    | 12:27PM INF Event 'die' received from frontends_dashy.1.rxvia8fimadhrd6fdu07dqiz0. Generating Homer config...
dashboards_homer-sd.1.6zdppva9ud9m@swarm-master    | 12:27PM INF Homer config was successfully generated and updated
dashboards_homer-sd.1.6zdppva9ud9m@swarm-master    | 12:27PM INF Event 'die' received from frontends_uptime-kuma.1.psywehcro0tjqtqaa5qq2zixk. Generating Homer config...
dashboards_homer-sd.1.6zdppva9ud9m@swarm-master    | 12:27PM INF Homer config was successfully generated and updated
dashboards_homer-sd.1.ntyny9cgtrir@swarm-master    | 12:27PM DBG Loading internal config
dashboards_homer-sd.1.ntyny9cgtrir@swarm-master    | 12:27PM INF Building Homer config from base config
dashboards_homer-sd.1.ntyny9cgtrir@swarm-master    | 12:27PM INF Homer config was successfully generated and updated
dashboards_homer-sd.1.ntyny9cgtrir@swarm-master    | 12:27PM INF Start watching for container creations and deletions
dashboards_homer-sd.1.ntyny9cgtrir@swarm-master    | 12:37PM INF Event 'start' received from frontends_uptime-kuma.1.qfjmfeong6rhmullelvrnxm8i. Generating Homer config...
dashboards_homer-sd.1.ntyny9cgtrir@swarm-master    | 12:37PM INF Homer config was successfully generated and updated
dashboards_homer-sd.1.ntyny9cgtrir@swarm-master    | 12:37PM INF Event 'start' received from frontends_dashy.1.lo752yrz6192zitujoc3lopv1. Generating Homer config...
dashboards_homer-sd.1.ntyny9cgtrir@swarm-master    | 12:37PM INF Homer config was successfully generated and updated
dashboards_homer-sd.1.ntyny9cgtrir@swarm-master    | 12:38PM INF Event 'health_status: healthy' received from frontends_uptime-kuma.1.qfjmfeong6rhmullelvrnxm8i. Generating Homer config...
dashboards_homer-sd.1.ntyny9cgtrir@swarm-master    | 12:38PM INF Homer config was successfully generated and updated
```
this is my docker compose stack file

```
# cat ../dashboards/homer/docker-compose.yml 
version: "3.7"

services:
  homer:
    image: b4bz/homer:22.02.1
    hostname: "homer"
    networks:
      - web
    volumes:
      - /data/homer/assets:/www/assets
    ports:
      - 8095:8080
    # Set any environmental variables
    environment:
      DOCKER_HOST: dockersocket
    deploy:
      labels:
          - "traefik.enable=true"
          - "traefik.http.routers.homer-http.rule=Host(`homer.home.local`)"
          - "traefik.http.routers.homer-http.entrypoints=web"
          - "traefik.http.routers.homer-http.service=homer-http-svc"
          - "traefik.http.services.homer-http-svc.loadbalancer.server.port=8080"
          - "traefik.http.services.homer-http-svc.loadbalancer.passhostheader=true"
          - "diun.enable=true"
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
           - "node.role==manager"

  homer-sd:
    image: ghcr.io/calvinbui/homer-service-discovery
    hostname: "homer-sd"
    networks:
      - web
    volumes:
      - /data/homer/assets/config.yml:/config.yml
      - /data/homer/sd/base.yml:/base.yml
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      labels:
          - "diun.enable=true"
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
           - "node.role==manager"

networks:
  web:
    external: true
    name: web
```

and this is my traefik-stack.yml

```
# cat traefik-stack.yml 
version: '3.7'

services:
  reverse-proxy:
    image: traefik:2.6
    hostname: "traefik"
    command:
      - "--api.dashboard=true"
      - "--providers.docker"
      - "--providers.docker.swarmMode=true"
      - "--entrypoints.web.address=:80"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.docker.network=web"
      - "--log.level=DEBUG"
      - "--log.filePath=/var/log/traefik.log"
      - "--accessLog.filePath=/var/log/access.log"
    ports:
      - "80:80"
      - "8080:8080"
    environment:
      DOCKER_HOST: dockersocket
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/log/traefik.log:/var/log/traefik.log
      - /var/log/access.log:/var/log/access.log
      - /home/ansible/stacks/traefik/static/traefik.yml:/traefik.yml
      - /home/ansible/stacks/traefik/config:/config/
    networks:
      - web
    deploy:
      labels:
          - "diun.enable=true"
          - "traefik.enable=true"
          - "traefik.http.routers.api.rule=Host(`traefik.home.local`)"
          - "traefik.http.routers.api.service=api@internal"
          # - "traefik.http.routers.api.middlewares=auth"
          # - "traefik.http.middlewares.auth.basicauth.users="
          # Dummy service for Swarm port detection. The port can be any valid integer value.
          - "traefik.http.services.dummy-svc.loadbalancer.server.port=9999"
          # Homer Service discovery label
          - "homer.enable=true"
          - "homer.service=Homelab"
          - "homer.name=traefik"
          - "homer.subtitle='traefik Reverse Proxy'"
          - "homer.icon='far fa-hand-peace'"
          - "homer.priority=2"
          - "homer.url='http://traefik.home.local'"
      mode: global
      placement:
        constraints: [node.role == manager]

networks:
  proxy:
    driver: bridge
    external: true

networks:
  web:
    driver: overlay
    attachable: true
    name: web


```

**Expected behavior**
A new service addition as shown in the example.

**Additional context**
in homer service discovery log noticed not sure why is it attempting to load dashy
